train_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes: [
            '背景', '旱地', '园地', '水田', '灌木林', 
            '乔木林', '疏林', '其它林地', '草地', '密集建筑区',
            '独立建筑', '农业大棚', '机场', '尾矿库', '露天采矿场',
            '露天采石场', '建筑工地', '墓地', '不透水面', '道路',
            '铁路', '桥梁', '广场', '体育场', '水域',
            '大坝（可发电）', '大坝（不可发电）', '沙漠', '裸地', '冰川', '云', '停车场', '光伏板'
        ]
      ignore_bg: false
      palette:  [
          [0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [7, 7, 7],[8, 8, 8], [9, 9, 9], [10, 10, 10], [11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15], [16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19],
                      [20, 20, 20], [21, 21, 21], [22, 22, 22], [23, 23, 23], [24, 24, 24], [25, 25, 25], [26, 26, 26], [27, 27, 27], [28, 28, 28], [29, 29, 29], [30, 30, 30], [31, 31, 31], [32, 32, 32]
        ]
      root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/XinTong512_new/train/images
      # root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/train/images
      root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/XinTong512_new/train/labels
      # root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/train/labels
      cache: none
      split_key: train
  wrapper:
    name: train
    args:
      inp_size: 512
      augment: false
  batch_size: 1
  num_workers: 8
val_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes: [
            '背景', '旱地', '园地', '水田', '灌木林', 
            '乔木林', '疏林', '其它林地', '草地', '密集建筑区',
            '独立建筑', '农业大棚', '机场', '尾矿库', '露天采矿场',
            '露天采石场', '建筑工地', '墓地', '不透水面', '道路',
            '铁路', '桥梁', '广场', '体育场', '水域',
            '大坝（可发电）', '大坝（不可发电）', '沙漠', '裸地', '冰川', '云', '停车场', '光伏板'
        ]
      ignore_bg: false
      palette:  [
          [0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [7, 7, 7],[8, 8, 8], [9, 9, 9], [10, 10, 10], [11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15], [16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19],
                      [20, 20, 20], [21, 21, 21], [22, 22, 22], [23, 23, 23], [24, 24, 24], [25, 25, 25], [26, 26, 26], [27, 27, 27], [28, 28, 28], [29, 29, 29], [30, 30, 30], [31, 31, 31], [32, 32, 32]
        ]
      root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/XinTong512_new/val/images
      # root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/val/images
      root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/XinTong512_new/val/labels
      # root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/val/labels
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 512
  batch_size: 1

test_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes: [
            '背景', '旱地', '园地', '水田', '灌木林', 
            '乔木林', '疏林', '其它林地', '草地', '密集建筑区',
            '独立建筑', '农业大棚', '机场', '尾矿库', '露天采矿场',
            '露天采石场', '建筑工地', '墓地', '不透水面', '道路',
            '铁路', '桥梁', '广场', '体育场', '水域',
            '大坝（可发电）', '大坝（不可发电）', '沙漠', '裸地', '冰川', '云', '停车场', '光伏板'
        ]
      ignore_bg: false
      palette:  [
          [0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [7, 7, 7],[8, 8, 8], [9, 9, 9], [10, 10, 10], [11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15], [16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19],
                      [20, 20, 20], [21, 21, 21], [22, 22, 22], [23, 23, 23], [24, 24, 24], [25, 25, 25], [26, 26, 26], [27, 27, 27], [28, 28, 28], [29, 29, 29], [30, 30, 30], [31, 31, 31], [32, 32, 32]
        ]

      root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/merge_data_1116/val/images
      root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/merge_data_1116/val/images
      cache: none
      split_key: test
  wrapper:
    name: test
    args:
      inp_size: 512
  batch_size: 1

eval_type: seg
sam_checkpoint: /public/home/daiwenxuan/project/pretrained_weights/sam_vit_h_4b8939.pth
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
  gt_rgb:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: sam_bf16_10b
  args:
    num_classes: 33
    inp_size: 512
    loss: iou
    loss_weight : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,1.0,1.0,1.0]
    encoder_mode:
      name: sam
      img_size: 512
      mlp_ratio: 4
      patch_size: 16
      qkv_bias: true
      use_rel_pos: true
      window_size: 14
      out_chans: 256
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      prompt_embed_dim: 256
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor
      embed_dim: 1280
      depth: 32
      num_heads: 16
      global_attn_indexes:
      - 7
      - 15
      - 23
      - 31
      # MoE相关设置
      moe_num_experts: 1412  # 专家数量，较少以减少显存
      moe_k: 1  # 选择的专家数量
      moe_noisy_gating: true  # 使用噪声门控
      moe_start_layer_index: 22  # 从第20层开始使用MoE
      moe_alternate: true  # 交替使用MoE
      moe_type: "ultra"  # 使用SparseSoftMoEBlock，可选: 'sparse', 'zero', 'ultra', 'soft'
      # CPU卸载和AMP设置
      use_cpu_offload: false  # 启用CPU卸载非关键张量，进一步减少显存
      offload_every_n_layers: 2  # 每4层Transformer进行一次卸载
      offload_non_blocking: True  # 使用非阻塞CPU卸载，减少性能影响
      use_amp: True  # 启用AMP混合精度
      amp_dtype: float16  # 使用FP16作为混合精度的数据类型
optimizer:
  name: adamw
  args:
    lr: 0.0003
lr_min: 1.0e-7
epoch_max: 200
training_settings:
  use_bf16: true
  use_deepspeed: false  # 设置为False使用DDP模式
  ddp_find_unused_parameters: true
  activation_checkpointing: true  # 启用激活检查点以减少显存使用
  grad_accum_steps: 4
  use_cpu_offload: false  # 启用CPU卸载非关键张量，进一步减少显存
  offload_every_n_layers: 1  # 每2层Transformer进行一次卸载
  offload_non_blocking: true  # 使用非阻塞CPU卸载，减少性能影响
  clip_grad_norm: 1.0

multi_step_lr:
  milestones:
  - 1
  gamma: 0.1
epoch_val: 2
epoch_save: 1
resume: last
work_dir: /public/home/daiwenxuan/project/fan/cwsam/save/
