train_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes: [
            '背景', '旱地', '园地', '水田', '灌木林', 
            '乔木林', '疏林', '其它林地', '草地', '密集建筑区',
            '独立建筑', '农业大棚', '机场', '尾矿库', '露天采矿场',
            '露天采石场', '建筑工地', '墓地', '不透水面', '道路',
            '铁路', '桥梁', '广场', '体育场', '水域',
            '大坝（可发电）', '大坝（不可发电）', '沙漠', '裸地', '冰川', '云', '停车场', '光伏板'
        ]
      ignore_bg: false
      palette:  [
          [0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [7, 7, 7],[8, 8, 8], [9, 9, 9], [10, 10, 10], [11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15], [16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19],
                      [20, 20, 20], [21, 21, 21], [22, 22, 22], [23, 23, 23], [24, 24, 24], [25, 25, 25], [26, 26, 26], [27, 27, 27], [28, 28, 28], [29, 29, 29], [30, 30, 30], [31, 31, 31], [32, 32, 32]
        ]
      root_path_1: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/train/images
      # root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/train/images
      root_path_2: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/train/labels
      # root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/train/labels
      cache: none
      split_key: train
  wrapper:
    name: train
    args:
      inp_size: 512
      augment: false
  batch_size: 4

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes: [
            '背景', '旱地', '园地', '水田', '灌木林', 
            '乔木林', '疏林', '其它林地', '草地', '密集建筑区',
            '独立建筑', '农业大棚', '机场', '尾矿库', '露天采矿场',
            '露天采石场', '建筑工地', '墓地', '不透水面', '道路',
            '铁路', '桥梁', '广场', '体育场', '水域',
            '大坝（可发电）', '大坝（不可发电）', '沙漠', '裸地', '冰川', '云', '停车场', '光伏板'
        ]
      ignore_bg: false
      palette:  [
          [0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [7, 7, 7],[8, 8, 8], [9, 9, 9], [10, 10, 10], [11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15], [16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19],
                      [20, 20, 20], [21, 21, 21], [22, 22, 22], [23, 23, 23], [24, 24, 24], [25, 25, 25], [26, 26, 26], [27, 27, 27], [28, 28, 28], [29, 29, 29], [30, 30, 30], [31, 31, 31], [32, 32, 32]
        ]
      root_path_1: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/val/images
      # root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/val/images
      root_path_2: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/val/labels
      # root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/val/labels
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 512
  batch_size: 1

test_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes: [
            '背景', '旱地', '园地', '水田', '灌木林', 
            '乔木林', '疏林', '其它林地', '草地', '密集建筑区',
            '独立建筑', '农业大棚', '机场', '尾矿库', '露天采矿场',
            '露天采石场', '建筑工地', '墓地', '不透水面', '道路',
            '铁路', '桥梁', '广场', '体育场', '水域',
            '大坝（可发电）', '大坝（不可发电）', '沙漠', '裸地', '冰川', '云', '停车场', '光伏板'
        ]
      ignore_bg: false
      palette:  [
          [0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [7, 7, 7],[8, 8, 8], [9, 9, 9], [10, 10, 10], [11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15], [16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19],
                      [20, 20, 20], [21, 21, 21], [22, 22, 22], [23, 23, 23], [24, 24, 24], [25, 25, 25], [26, 26, 26], [27, 27, 27], [28, 28, 28], [29, 29, 29], [30, 30, 30], [31, 31, 31], [32, 32, 32]
        ]

      root_path_1: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/val_test/images
      root_path_2: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/val_test/images
      cache: none
      split_key: test
  wrapper:
    name: test
    args:
      inp_size: 512
  batch_size: 1

eval_type: seg
sam_checkpoint: /mnt/fanfq/data/fan/cwsam/save/XinTong_sam_vit_h_moe_3b/model_epoch_121.pth
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
  gt_rgb:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: sam_hierarchical_moe_10b
  args:
    num_classes: 33
    inp_size: 512
    loss: iou
    loss_weight : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,1.0,1.0,1.0]
    encoder_mode:
      name: sam_hierarchical_moe
      img_size: 512
      mlp_ratio: 4
      patch_size: 16
      qkv_bias: true
      use_rel_pos: true
      window_size: 14
      out_chans: 256
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      prompt_embed_dim: 256
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor
      embed_dim: 1280
      depth: 38
      num_heads: 16
      global_attn_indexes:
      - 7
      - 15
      - 23
      - 31
      - 39
      moe_num_expert_groups: 3
      moe_experts_per_group: 16
      moe_k_groups: 2
      moe_k_experts: 4
      moe_noisy_gating: true
      moe_start_layer_index: 24
      use_checkpoint: true
optimizer:
  name: adamw 
  args:
    lr: 0.0002
lr_min: 1.0e-7
epoch_max: 200



multi_step_lr:
  milestones:
  - 1
  gamma: 0.1
epoch_val: 1
epoch_save: 1
# resume: 10
# work_dir: /public/home/daiwenxuan/project/fan/cwsam/save/XinTong_sam_vit_h