train_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes: [
            '背景', '旱地', '园地', '水田', '灌木林', 
            '乔木林', '疏林', '其它林地', '草地', '密集建筑区',
            '独立建筑', '农业大棚', '机场', '尾矿库', '露天采矿场',
            '露天采石场', '建筑工地', '墓地', '不透水面', '道路',
            '铁路', '桥梁', '广场', '体育场', '水域',
            '大坝（可发电）', '大坝（不可发电）', '沙漠', '裸地', '冰川', '云', '停车场', '光伏板'
        ]
      ignore_bg: false
      palette:  [
          [0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [7, 7, 7],[8, 8, 8], [9, 9, 9], [10, 10, 10], [11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15], [16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19],
                      [20, 20, 20], [21, 21, 21], [22, 22, 22], [23, 23, 23], [24, 24, 24], [25, 25, 25], [26, 26, 26], [27, 27, 27], [28, 28, 28], [29, 29, 29], [30, 30, 30], [31, 31, 31], [32, 32, 32]
        ]
      root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/XinTong512/train/images
      # root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/train/images
      root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/XinTong512/train/labels
      # root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/train/labels
      cache: none
      split_key: train
  wrapper:
    name: train
    args:
      inp_size: 512
      augment: false
  batch_size: 1

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes: [
            '背景', '旱地', '园地', '水田', '灌木林', 
            '乔木林', '疏林', '其它林地', '草地', '密集建筑区',
            '独立建筑', '农业大棚', '机场', '尾矿库', '露天采矿场',
            '露天采石场', '建筑工地', '墓地', '不透水面', '道路',
            '铁路', '桥梁', '广场', '体育场', '水域',
            '大坝（可发电）', '大坝（不可发电）', '沙漠', '裸地', '冰川', '云', '停车场', '光伏板'
        ]
      ignore_bg: false
      palette:  [
          [0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [7, 7, 7],[8, 8, 8], [9, 9, 9], [10, 10, 10], [11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15], [16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19],
                      [20, 20, 20], [21, 21, 21], [22, 22, 22], [23, 23, 23], [24, 24, 24], [25, 25, 25], [26, 26, 26], [27, 27, 27], [28, 28, 28], [29, 29, 29], [30, 30, 30], [31, 31, 31], [32, 32, 32]
        ]
      root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/XinTong512/val/images
      # root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/val/images
      root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/XinTong512/val/labels
      # root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/beijing_ai_data_1027/val/labels
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 512
  batch_size: 1

test_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes: [
            '背景', '旱地', '园地', '水田', '灌木林', 
            '乔木林', '疏林', '其它林地', '草地', '密集建筑区',
            '独立建筑', '农业大棚', '机场', '尾矿库', '露天采矿场',
            '露天采石场', '建筑工地', '墓地', '不透水面', '道路',
            '铁路', '桥梁', '广场', '体育场', '水域',
            '大坝（可发电）', '大坝（不可发电）', '沙漠', '裸地', '冰川', '云', '停车场', '光伏板'
        ]
      ignore_bg: false
      palette:  [
          [0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6], [7, 7, 7],[8, 8, 8], [9, 9, 9], [10, 10, 10], [11, 11, 11], [12, 12, 12], [13, 13, 13], [14, 14, 14], [15, 15, 15], [16, 16, 16], [17, 17, 17], [18, 18, 18], [19, 19, 19],
                      [20, 20, 20], [21, 21, 21], [22, 22, 22], [23, 23, 23], [24, 24, 24], [25, 25, 25], [26, 26, 26], [27, 27, 27], [28, 28, 28], [29, 29, 29], [30, 30, 30], [31, 31, 31], [32, 32, 32]
        ]

      root_path_1: /public/home/daiwenxuan/project/fan/data/dataset/merge_data_1116/val/images
      root_path_2: /public/home/daiwenxuan/project/fan/data/dataset/merge_data_1116/val/images
      cache: none
      split_key: test
  wrapper:
    name: test
    args:
      inp_size: 512
  batch_size: 1

eval_type: seg
sam_checkpoint: /public/home/daiwenxuan/project/pretrained_weights/sam_vit_h_4b8939.pth
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
  gt_rgb:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: sam_moe_ultra
  args:
    num_classes: 33
    inp_size: 512
    loss: iou
    loss_weight : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,1.0,1.0,1.0]
    encoder_mode:
      name: sam
      img_size: 512
      mlp_ratio: 4
      patch_size: 16
      qkv_bias: true
      use_rel_pos: true
      window_size: 14
      out_chans: 256
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      prompt_embed_dim: 256
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor
      embed_dim: 1280
      depth: 32
      num_heads: 16
      global_attn_indexes:
      - 7
      - 15
      - 23
      - 31
            # 超稀疏MoE配置 - 极大专家数量，极小激活
      moe_num_experts: 2048       # 超大专家数量
      moe_k: 1                      # 每个token只选择1个专家
      moe_noisy_gating: true
      moe_start_layer_index: 8      # 从第8层开始使用MoE
      moe_alternate: false          # 所有后续层都使用MoE
      use_checkpoint: true          # 启用梯度检查点
      
      # UltraSparseMoE特有配置
      moe_type: "ultra_sparse"      # 使用超稀疏MoE
      expert_rank: 48               # 专家低秩分解维度
      max_active_experts: 512       # 最大活跃专家数
      expert_lifetime: 3000         # 专家生命周期
      usage_threshold: 0.002        # 使用率阈值
      shared_expert_ratio: 0.02     # 共享专家比例
      expert_dropout: 0.05          # 专家dropout
      load_balancing_loss_coef: 0.005 # 负载均衡损失系数
      
      # 显存优化配置
      use_gradient_checkpointing: true
      offload_unused_experts: true
      compress_expert_weights: true
      
      # 容量控制
      moe_capacity_factor: 0.25     # 极低容量因子
      moe_min_capacity: 1           # 最小容量
      moe_drop_tokens: true         # 启用token丢弃
optimizer:
  name: adamw
  args:
    lr: 0.00005  # 更低的学习率适应超稀疏结构
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: 1.0e-8

lr_min: 1.0e-8
epoch_max: 200
# 训练设置 - 极致显存优化
training_settings:
  precision: bf16
  ddp_find_unused_parameters: false
  clip_grad_norm: 1  # 更小的梯度裁剪
  accumulate_grad_batches: 8  # 大梯度累积

# DeepSpeed Zero配置 - 最大显存节省
deepspeed:
  enabled: true
  config:
    train_batch_size: 32  # 全局batch size
    micro_batch_size: 2   # 微批次大小
    gradient_accumulation_steps: 8
    
    # BF16配置
    bf16:
      enabled: true
      loss_scale: 0
      initial_scale_power: 16
      loss_scale_window: 1000
      hysteresis: 2
      min_loss_scale: 1
    
    # Zero Stage 3 - 最大显存节省
    zero_optimization:
      stage: 3
      offload_optimizer:
        device: cpu
        pin_memory: true
        buffer_count: 4
        fast_init: false
      offload_param:
        device: cpu
        pin_memory: true
        buffer_count: 5
        buffer_size: 1e8
        max_in_cpu: 1e9
      overlap_comm: true
      contiguous_gradients: true
      sub_group_size: 1e9
      reduce_bucket_size: 2e8
      stage3_prefetch_bucket_size: 2e7
      stage3_param_persistence_threshold: 1e4
      stage3_max_live_parameters: 5e8
      stage3_max_reuse_distance: 1e9
      stage3_gather_16bit_weights_on_model_save: true
      gather_fp16_weights_on_model_save: false
    
    # 激活检查点 - 最大化显存节省
    activation_checkpointing:
      partition_activations: true
      cpu_checkpointing: true
      contiguous_memory_optimization: true
      number_checkpoints: 8
      synchronize_checkpoint_boundary: true
      profile: false
    
    # 通信优化
    comms_logger:
      enabled: false
    
    # 内存监控
    memory_breakdown:
      enabled: true
    
    # 编译优化
    compile:
      enabled: false  # 暂时禁用以避免兼容性问题
multi_step_lr:
  milestones:
  - 1
  gamma: 0.1
epoch_val: 1
epoch_save: 1
training_settings:
  precision: 'amp'
# resume: 30
# work_dir: /public/home/daiwenxuan/project/fan/cwsam/save/XinTong_sam_vit_h
# 日志配置
log_level: INFO
log_interval: 50

# 专家管理配置
expert_management:
  enabled: true
  log_expert_usage: true
  save_expert_stats: true
  expert_pruning_interval: 1000  # 每1000步进行一次专家剪枝
  
# 内存监控配置
memory_monitoring:
  enabled: true
  log_interval: 100
  save_memory_profile: true
  alert_threshold: 0.9  # 显存使用率超过90%时报警

# 实验配置
experiment:
  name: "ultra_sparse_moe_1024_experts"
  description: "使用1024个专家的超稀疏MoE实验，每次只激活1个专家"
  tags: ["ultra_sparse", "moe", "memory_efficient", "1024_experts"]