train_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes:
      - "\u80CC\u666F"
      - "\u65F1\u5730"
      - "\u56ED\u5730"
      - "\u6C34\u7530"
      - "\u704C\u6728\u6797"
      - "\u4E54\u6728\u6797"
      - "\u758F\u6797"
      - "\u5176\u5B83\u6797\u5730"
      - "\u8349\u5730"
      - "\u5BC6\u96C6\u5EFA\u7B51\u533A"
      - "\u72EC\u7ACB\u5EFA\u7B51"
      - "\u519C\u4E1A\u5927\u68DA"
      - "\u673A\u573A"
      - "\u5C3E\u77FF\u5E93"
      - "\u9732\u5929\u91C7\u77FF\u573A"
      - "\u9732\u5929\u91C7\u77F3\u573A"
      - "\u5EFA\u7B51\u5DE5\u5730"
      - "\u5893\u5730"
      - "\u4E0D\u900F\u6C34\u9762"
      - "\u9053\u8DEF"
      - "\u94C1\u8DEF"
      - "\u6865\u6881"
      - "\u5E7F\u573A"
      - "\u4F53\u80B2\u573A"
      - "\u6C34\u57DF"
      - "\u5927\u575D\uFF08\u53EF\u53D1\u7535\uFF09"
      - "\u5927\u575D\uFF08\u4E0D\u53EF\u53D1\u7535\uFF09"
      - "\u6C99\u6F20"
      - "\u88F8\u5730"
      - "\u51B0\u5DDD"
      - "\u4E91"
      - "\u505C\u8F66\u573A"
      - "\u5149\u4F0F\u677F"
      ignore_bg: false
      palette:
      - - 0
        - 0
        - 0
      - - 1
        - 1
        - 1
      - - 2
        - 2
        - 2
      - - 3
        - 3
        - 3
      - - 4
        - 4
        - 4
      - - 5
        - 5
        - 5
      - - 6
        - 6
        - 6
      - - 7
        - 7
        - 7
      - - 8
        - 8
        - 8
      - - 9
        - 9
        - 9
      - - 10
        - 10
        - 10
      - - 11
        - 11
        - 11
      - - 12
        - 12
        - 12
      - - 13
        - 13
        - 13
      - - 14
        - 14
        - 14
      - - 15
        - 15
        - 15
      - - 16
        - 16
        - 16
      - - 17
        - 17
        - 17
      - - 18
        - 18
        - 18
      - - 19
        - 19
        - 19
      - - 20
        - 20
        - 20
      - - 21
        - 21
        - 21
      - - 22
        - 22
        - 22
      - - 23
        - 23
        - 23
      - - 24
        - 24
        - 24
      - - 25
        - 25
        - 25
      - - 26
        - 26
        - 26
      - - 27
        - 27
        - 27
      - - 28
        - 28
        - 28
      - - 29
        - 29
        - 29
      - - 30
        - 30
        - 30
      - - 31
        - 31
        - 31
      - - 32
        - 32
        - 32
      root_path_1: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/train/images
      root_path_2: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/train/labels
      cache: none
      split_key: train
  wrapper:
    name: train
    args:
      inp_size: 512
      augment: false
  batch_size: 6
val_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes:
      - "\u80CC\u666F"
      - "\u65F1\u5730"
      - "\u56ED\u5730"
      - "\u6C34\u7530"
      - "\u704C\u6728\u6797"
      - "\u4E54\u6728\u6797"
      - "\u758F\u6797"
      - "\u5176\u5B83\u6797\u5730"
      - "\u8349\u5730"
      - "\u5BC6\u96C6\u5EFA\u7B51\u533A"
      - "\u72EC\u7ACB\u5EFA\u7B51"
      - "\u519C\u4E1A\u5927\u68DA"
      - "\u673A\u573A"
      - "\u5C3E\u77FF\u5E93"
      - "\u9732\u5929\u91C7\u77FF\u573A"
      - "\u9732\u5929\u91C7\u77F3\u573A"
      - "\u5EFA\u7B51\u5DE5\u5730"
      - "\u5893\u5730"
      - "\u4E0D\u900F\u6C34\u9762"
      - "\u9053\u8DEF"
      - "\u94C1\u8DEF"
      - "\u6865\u6881"
      - "\u5E7F\u573A"
      - "\u4F53\u80B2\u573A"
      - "\u6C34\u57DF"
      - "\u5927\u575D\uFF08\u53EF\u53D1\u7535\uFF09"
      - "\u5927\u575D\uFF08\u4E0D\u53EF\u53D1\u7535\uFF09"
      - "\u6C99\u6F20"
      - "\u88F8\u5730"
      - "\u51B0\u5DDD"
      - "\u4E91"
      - "\u505C\u8F66\u573A"
      - "\u5149\u4F0F\u677F"
      ignore_bg: false
      palette:
      - - 0
        - 0
        - 0
      - - 1
        - 1
        - 1
      - - 2
        - 2
        - 2
      - - 3
        - 3
        - 3
      - - 4
        - 4
        - 4
      - - 5
        - 5
        - 5
      - - 6
        - 6
        - 6
      - - 7
        - 7
        - 7
      - - 8
        - 8
        - 8
      - - 9
        - 9
        - 9
      - - 10
        - 10
        - 10
      - - 11
        - 11
        - 11
      - - 12
        - 12
        - 12
      - - 13
        - 13
        - 13
      - - 14
        - 14
        - 14
      - - 15
        - 15
        - 15
      - - 16
        - 16
        - 16
      - - 17
        - 17
        - 17
      - - 18
        - 18
        - 18
      - - 19
        - 19
        - 19
      - - 20
        - 20
        - 20
      - - 21
        - 21
        - 21
      - - 22
        - 22
        - 22
      - - 23
        - 23
        - 23
      - - 24
        - 24
        - 24
      - - 25
        - 25
        - 25
      - - 26
        - 26
        - 26
      - - 27
        - 27
        - 27
      - - 28
        - 28
        - 28
      - - 29
        - 29
        - 29
      - - 30
        - 30
        - 30
      - - 31
        - 31
        - 31
      - - 32
        - 32
        - 32
      root_path_1: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/val/images
      root_path_2: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/val/labels
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 512
  batch_size: 1
test_dataset:
  dataset:
    name: paired-image-folders
    args:
      classes:
      - "\u80CC\u666F"
      - "\u65F1\u5730"
      - "\u56ED\u5730"
      - "\u6C34\u7530"
      - "\u704C\u6728\u6797"
      - "\u4E54\u6728\u6797"
      - "\u758F\u6797"
      - "\u5176\u5B83\u6797\u5730"
      - "\u8349\u5730"
      - "\u5BC6\u96C6\u5EFA\u7B51\u533A"
      - "\u72EC\u7ACB\u5EFA\u7B51"
      - "\u519C\u4E1A\u5927\u68DA"
      - "\u673A\u573A"
      - "\u5C3E\u77FF\u5E93"
      - "\u9732\u5929\u91C7\u77FF\u573A"
      - "\u9732\u5929\u91C7\u77F3\u573A"
      - "\u5EFA\u7B51\u5DE5\u5730"
      - "\u5893\u5730"
      - "\u4E0D\u900F\u6C34\u9762"
      - "\u9053\u8DEF"
      - "\u94C1\u8DEF"
      - "\u6865\u6881"
      - "\u5E7F\u573A"
      - "\u4F53\u80B2\u573A"
      - "\u6C34\u57DF"
      - "\u5927\u575D\uFF08\u53EF\u53D1\u7535\uFF09"
      - "\u5927\u575D\uFF08\u4E0D\u53EF\u53D1\u7535\uFF09"
      - "\u6C99\u6F20"
      - "\u88F8\u5730"
      - "\u51B0\u5DDD"
      - "\u4E91"
      - "\u505C\u8F66\u573A"
      - "\u5149\u4F0F\u677F"
      ignore_bg: false
      palette:
      - - 0
        - 0
        - 0
      - - 1
        - 1
        - 1
      - - 2
        - 2
        - 2
      - - 3
        - 3
        - 3
      - - 4
        - 4
        - 4
      - - 5
        - 5
        - 5
      - - 6
        - 6
        - 6
      - - 7
        - 7
        - 7
      - - 8
        - 8
        - 8
      - - 9
        - 9
        - 9
      - - 10
        - 10
        - 10
      - - 11
        - 11
        - 11
      - - 12
        - 12
        - 12
      - - 13
        - 13
        - 13
      - - 14
        - 14
        - 14
      - - 15
        - 15
        - 15
      - - 16
        - 16
        - 16
      - - 17
        - 17
        - 17
      - - 18
        - 18
        - 18
      - - 19
        - 19
        - 19
      - - 20
        - 20
        - 20
      - - 21
        - 21
        - 21
      - - 22
        - 22
        - 22
      - - 23
        - 23
        - 23
      - - 24
        - 24
        - 24
      - - 25
        - 25
        - 25
      - - 26
        - 26
        - 26
      - - 27
        - 27
        - 27
      - - 28
        - 28
        - 28
      - - 29
        - 29
        - 29
      - - 30
        - 30
        - 30
      - - 31
        - 31
        - 31
      - - 32
        - 32
        - 32
      root_path_1: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/val_test/images
      root_path_2: /mnt/fanfq/data/fan/data/dataset/XinTong512_new/val_test/images
      cache: none
      split_key: test
  wrapper:
    name: test
    args:
      inp_size: 512
  batch_size: 1
eval_type: seg
sam_checkpoint: /mnt/fanfq/data/fan/cwsam/save/XinTong_sam_vit_h_moe_3b/model_epoch_121.pth
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
  gt_rgb:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: sam_hierarchical_moe_10b
  args:
    num_classes: 33
    inp_size: 512
    loss: iou
    loss_weight:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    encoder_mode:
      name: sam_hierarchical_moe
      img_size: 512
      mlp_ratio: 4
      patch_size: 16
      qkv_bias: true
      use_rel_pos: true
      window_size: 14
      out_chans: 256
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      prompt_embed_dim: 256
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor
      embed_dim: 1280
      depth: 38
      num_heads: 16
      global_attn_indexes:
      - 7
      - 15
      - 23
      - 31
      - 39
      moe_num_expert_groups: 3
      moe_experts_per_group: 16
      moe_k_groups: 1
      moe_k_experts: 4
      moe_noisy_gating: true
      moe_start_layer_index: 24
      use_checkpoint: true
optimizer:
  name: adamw
  args:
    lr: 0.0002
lr_min: 1.0e-07
epoch_max: 200
multi_step_lr:
  milestones:
  - 1
  gamma: 0.1
epoch_val: 1
epoch_save: 1
